gezginler mvc projesi son hali/gezginler/gezginler/Areas/admin/Controllers/AdminhomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace gezginler.Areas.admin.Controllers
{
    public class AdminhomeController : Controller
    {
        // GET: admin/Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Anasayfayadon()
        {
            return RedirectToAction("Index", "../Home");
        }

        public ActionResult Cikisyap()
        {
            return RedirectToAction("cikis", "../Home");
        }
    }
}

gezginler mvc projesi son hali/gezginler/gezginler/Areas/admin/Controllers/ResimController.cs
using gezginler.Areas.admin.Models;
using gezginler.Data;
using gezginler.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace gezginler.Areas.admin.Controllers
{
    public class ResimController : Controller
    {
        MvcProjesiContext dbcontext = new MvcProjesiContext();
        // GET: admin/Resim
        public ActionResult Index()
        {
           // var dbcontext = new MvcProjesiContext();
            var model = dbcontext.Resims.OrderByDescending(x => x.ResimId).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        const string ImageFolderPath = "/Content/img/";

        public ActionResult ResimAdd(ResimModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (model.Resim != null && model.Resim.ContentLength > 0)
                {
                    fileName = model.Resim.FileName;
                    var path = Path.Combine(Server.MapPath("~"+ImageFolderPath), fileName);
                    model.Resim.SaveAs(path);
                }

                Resim resim = new Resim();
                resim.Resimyol =ImageFolderPath+ fileName;
                dbcontext.Resims.Add(resim);
                dbcontext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Metinindex()
        {
            // var dbcontext = new MvcProjesiContext();
            var modl = dbcontext.Rehbers.OrderByDescending(x => x.RehberId).ToList();
            return View(modl);
        }

        public ActionResult Metinekle()
        {
            return View();
        }
        public ActionResult MetinAdd(Rehber modl)
        {
            if (ModelState.IsValid)
            {
                dbcontext.Rehbers.Add(modl);
                dbcontext.SaveChanges();
            }
            return RedirectToAction("Metinindex");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = dbcontext.Resims.Find(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Resim model)
        {
            if (ModelState.IsValid)
            {
               
                dbcontext.Resims.Attach(model);
                dbcontext.Entry(model).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
}

gezginler mvc projesi son hali/gezginler/gezginler/Areas/admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/datepicker3.css" rel="stylesheet">
    <link href="~/assets/css/styles.css" rel="stylesheet">
    <!--Icons-->
    <script src="~/assets/js/lumino.glyphs.js"></script>

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>ADMIN</span>PANELI</a>
                <ul class="user-menu">
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> User <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @*<li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
                            <li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>*@
                            <li><a href=@Url.Action("Anasayfayadon","Adminhome")><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Çıkış Yap</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div><!-- /.container-fluid -->
    </nav>

    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <form role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
        </form>
        <ul class="nav menu">

            <li><a href=@Url.Action("Index","Adminhome")><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>
            @*<li><a href="index.html"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>
            <li><a href="widgets.html"><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Widgets</a></li>
            <li><a href="charts.html"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> Charts</a></li>*@
            
            <li><a href=@Url.Action("Add","Resim")><svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> Resim Ekle</a></li>
            <li><a href=@Url.Action("Index","Resim")><svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> Eklenen resimler</a></li>
            <li><a href=@Url.Action("Metinekle","Resim")><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Metin Ekle</a></li>
            <li><a href=@Url.Action("MetinIndex","Resim")><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Eklenen Metinler</a></li>
            @*<li><a href="panels.html"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Alerts &amp; Panels</a></li>*@
           
           
            <li role="presentation" class="divider"></li>
            <li><a href=@Url.Action("Anasayfayadon","Adminhome")><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Anasayfa</a></li>
            
        </ul>
    </div><!--/.sidebar-->

    @RenderBody()

    <script src="~/assets/js/jquery-1.11.1.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/chart.min.js"></script>
    <script src="~/assets/js/chart-data.js"></script>
    <script src="~/assets/js/easypiechart.js"></script>
    <script src="~/assets/js/easypiechart-data.js"></script>
    <script src="~/assets/js/bootstrap-datepicker.js"></script>
    <script src="~/assets/js/bootstrap-table.js"></script>
    <script>
		$('#calendar').datepicker({
		});

		!function ($) {
		    $(document).on("click","ul.nav li.parent > a > span.icon", function(){
		        $(this).find('em:first').toggleClass("glyphicon-minus");
		    });
		    $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
		}(window.jQuery);

		$(window).on('resize', function () {
		  if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
		})
		$(window).on('resize', function () {
		  if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
		})
    </script>
</body>

</html>